import Head from "next/head";
import Image from "next/image";
import logomain from "../public/logomain.png";
import logo from "../public/logo.png";
import Link from "next/link";
import arrow from "../public/arrow.svg";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>NEAR Dev 101</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="max-w-screen-xl mx-auto">
        <nav className="max-w-screen-xl mx-auto fixed top-0 left-0 right-0 flex justify-between">
          <div className="flex gap-3 items-center">
            <div className="border-r-2 border-neutral-300 px-5">
              <Link href={"/"}>
                <Image src={logomain} width={100} alt="" />
              </Link>
            </div>
            <div className="">
              <Link href={"/"}>
                <Image src={logo} width={100} alt="" />
              </Link>
            </div>
          </div>
          <div className="flex gap-x-10 items-center">
            <Link href={"/course"}>Start The Course</Link>
            <Link
              href={"/course"}
              className="px-4 py-1 bg-slate-900  duration-200 rounded-full text-white"
            >
              Create Wallet
            </Link>
          </div>
        </nav>

        {/* Hero section  */}
        <div className="pt-44 max-w-screen-lg h mx-auto text-center">
          <div className="px-28 space-y-10">
            <h2 className="text-6xl font-medium">
              Get {" "}
              <span className="text-transparent bg-clip-text bg-gradient-to-b from-indigo-500 to-teal-300">
                NEAR
              </span> {" "}
              Certified!
            </h2>
            <p className="text-neutral-500 text-lg">
              We, in NEAR Balkans, know how important it is to have regional and
              local support. Now you can become NEAR certified in a regional
              language of preference and connect with our team to support your
              further growth within the NEAR ecosystem.
            </p>
          </div>
          <Link href={"/"} className="flex justify-center px-20 mt-24">
            <Image src={arrow} alt="" />
          </Link>
          <h3 className="pt-24 inline-flex justify-center text-5xl font-medium w-[30rem]">
            Making your NEAR learning easy.
          </h3>
        </div>
      </main>

      <footer className=""></footer>
    </div>
  );
}
